spring:
  sql:
    init:
      mode: always
  application:
    name: usermanagement-system
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:dev}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  logging:
    level:
      root: debug